In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get no. of dimension of numpy arrays
b.ndim

2

In [6]:
#Get shape
a.shape

(3,)

In [7]:
# Get type
a.dtype

dtype('int64')

In [8]:
# we can also specify the data type while creating the numpy array
a1 = np.array([1,2,3], dtype='int16')
a1.dtype

dtype('int16')

In [9]:
# Get size (in bytes)
a1.itemsize 

2

In [10]:
# Get total size
a1.size * a1.itemsize # a.size = 3 (no. of elements) & a.itemsize = 2 bytes (size of a single item)

6

### Accessing/Changing specific elements, rows, columns etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a.shape

(2, 7)

In [13]:
# Get a specific element [row, column]
print(a[1,5])
# can also use the -ve notation
print(a[1,-2])

13
13


In [14]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:,5]

array([ 6, 13])

In [16]:
# Getting little more fancy [start_index:end_index:step_size]
print(a[0, 1:6:2])
print(a[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [17]:
# To update an element
a[1,6] = 100
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13, 100]])

In [18]:
# To update a column
a[:,1] = 0 # to change the all the values in the columns to a specific value
a[:,0] = [4,3]
a

array([[  4,   0,   3,   4,   5,   6,   7],
       [  3,   0,  10,  11,  12,  13, 100]])

In [19]:
# 3D Example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get specific element (work outside in)
print(b[0,1,1]) # [row, column, element]
print(b[1,1,0])
print(b[1])

4
7
[[5 6]
 [7 8]]


In [21]:
# replace
print(b[:,1,:])
b[:,1,:] = [[9,9],[8,8]]
b 

[[3 4]
 [7 8]]


array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [22]:
# All 0s matrix
print(np.zeros(5)) # 1D
print()
print(np.zeros((2,3))) # 2D
print()
print(np.zeros((2,3,3))) # 3D

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
# All 1s matrix
np.ones((4,2,5), dtype='int32')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [24]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [25]:
# Any other number (full_like)
np.full_like(a, 4)  # it creates an array with the shape of 'a' filled with 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Random decimal numbers
print(np.random.rand(4,2))
print()
np.random.randint(-4,8, size=(3,3))

[[0.81752753 0.51534188]
 [0.33104379 0.08483279]
 [0.32741941 0.7675639 ]
 [0.25940298 0.35993475]]



array([[-3,  4, -3],
       [ 2,  1, -2],
       [ 7,  4, -4]], dtype=int32)

In [27]:
# For identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
# Transpose of a matrix
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Transpose of A
A_transpose = A.T
print("Transpose of matrix A:\n", A_transpose)

Transpose of matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
# Trace of a matrix
trace_A = np.trace(A)
print("Trace of matrix A:", trace_A)


Trace of matrix A: 15


In [ ]:
# Matrix multiplication

# Define two matrices
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Method 1: Using np.dot()
result1 = np.dot(A, B)

# Method 2: Using @ operator (Recommended)
result2 = A @ B

# Method 3: Using np.matmul()
result3 = np.matmul(A, B)

# Print results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication using np.dot():\n", result1)
print("Matrix Multiplication using @ operator:\n", result2)
print("Matrix Multiplication using np.matmul():\n", result3)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication using np.dot():
 [[19 22]
 [43 50]]
Matrix Multiplication using @ operator:
 [[19 22]
 [43 50]]
Matrix Multiplication using np.matmul():
 [[19 22]
 [43 50]]
