In [235]:
import numpy as np

In [236]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [237]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [238]:
# Get no. of dimension of numpy arrays
b.ndim

2

In [239]:
#Get shape
a.shape

(3,)

In [240]:
# Get type
a.dtype

dtype('int64')

In [241]:
# we can also specify the data type while creating the numpy array
a1 = np.array([1,2,3], dtype='int16')
a1.dtype

dtype('int16')

In [242]:
# Get size (in bytes)
a1.itemsize 

2

In [243]:
# Get total size
a1.size * a1.itemsize # a.size = 3 (no. of elements) & a.itemsize = 2 bytes (size of a single item)

6

### Accessing/Changing specific elements, rows, columns etc

In [244]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [245]:
a.shape

(2, 7)

In [246]:
# Get a specific element [row, column]
print(a[1,5])
# can also use the -ve notation
print(a[1,-2])

13
13


In [247]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [248]:
# Get a specific column
a[:,5]

array([ 6, 13])

In [249]:
# Getting little more fancy [start_index:end_index:step_size]
print(a[0, 1:6:2])
print(a[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [250]:
# To update an element
a[1,6] = 100
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13, 100]])

In [251]:
# To update a column
a[:,1] = 0 # to change the all the values in the columns to a specific value
a[:,0] = [4,3]
a

array([[  4,   0,   3,   4,   5,   6,   7],
       [  3,   0,  10,  11,  12,  13, 100]])

In [252]:
# 3D Example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [253]:
# Get specific element (work outside in)
print(b[0,1,1]) # [row, column, element]
print(b[1,1,0])
print(b[1])

4
7
[[5 6]
 [7 8]]


In [254]:
# replace
print(b[:,1,:])
b[:,1,:] = [[9,9],[8,8]]
b 

[[3 4]
 [7 8]]


array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [255]:
# All 0s matrix
print(np.zeros(5)) # 1D (column)
print()
print(np.zeros((2,3))) # 2D (row,column)
print()
print(np.zeros((2,3,3))) # 3D (-,row,column)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [256]:
# All 1s matrix
np.ones((4,2,5), dtype='int32')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [257]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [258]:
# Any other number (full_like)
np.full_like(a, 4)  # it creates an array with the shape of 'a' filled with 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

### Random

In [259]:
# Random decimal/float numbers
print(np.random.rand(4,2))
print()

print(np.random.randint(-4,8, size=(3,3)))

[[0.76636514 0.73809948]
 [0.51525756 0.94343159]
 [0.07929809 0.22479681]
 [0.2152059  0.35639289]]

[[ 2  0 -1]
 [-3  3 -3]
 [-4  3  7]]


In [260]:
# Shuffling
x = np.array([1,2,3,4,5])
np.random.shuffle(x) # shuffles the values of x in place
print(x)

y = np.random.permutation(x) # creates a new array and leaves the original array unchanged
print(y)

[2 1 3 4 5]
[2 4 3 5 1]


In [261]:
x = np.random.choice([1,2,3,4,5])
print(x)

y = np.random.choice([1,2,3,4,5],size=(3,5))
print(y)

5
[[3 1 4 1 4]
 [2 4 4 4 2]
 [4 5 2 1 3]]


In [262]:
# For identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [263]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [264]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print()
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [265]:
# Copying arrays (be careful!)

a = np.array([1,2,3])
# b = a 
# b[0] = 4
# print(b)
# print(a) # a also changed

# to properly copy
b=a.copy()
b[0] = 4
print(a)
print(b)

[1 2 3]
[4 2 3]


### Mathematics

In [266]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [267]:
# Element wise operation
a + 2

array([3, 4, 5, 6])

In [268]:
a - 2

array([-1,  0,  1,  2])

In [269]:
a * 2

array([2, 4, 6, 8])

In [270]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [271]:
a += 2
a

array([3, 4, 5, 6])

In [272]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [273]:
a * b

array([3, 0, 5, 0])

In [274]:
a ** 2

array([ 9, 16, 25, 36])

In [275]:
np.sin(a) # cos, tan etc.

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

#### Linear Algibra

In [279]:
a = np.full((2,3),1)
print(a)

b = np.full((3,2),2)
print(b)

c = np.full((2,3),4)
print(c)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[4 4 4]
 [4 4 4]]


In [ ]:
print(a @ b) # matrix multiplication
print(a + c) # matrix addition
print(a - c) # matrix subtraction

[[6 6]
 [6 6]]
[[5 5 5]
 [5 5 5]]
[[-3 -3 -3]
 [-3 -3 -3]]


In [ ]:
# Transpose of a matrix
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Transpose of A
A_transpose = A.T
print("Transpose of matrix A:\n", A_transpose)

Transpose of matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# Trace of a matrix
trace_A = np.trace(A)
print("Trace of matrix A:", trace_A)


Trace of matrix A: 15


In [ ]:
# Inverse of a matrix
A = np.array([[1, 2],
              [3, 4]])

print(A)

B = np.linalg.inv(A)
print(B)

I = A.dot(B)
print(I)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [ ]:
# Matrix multiplication

# Define two matrices
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Method 1: Using np.dot()
result1 = np.dot(A, B)

# Method 2: Using @ operator (Recommended)
result2 = A @ B

# Method 3: Using np.matmul()
result3 = np.matmul(A, B)

# Print results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication using np.dot():\n", result1)
print("Matrix Multiplication using @ operator:\n", result2)
print("Matrix Multiplication using np.matmul():\n", result3)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication using np.dot():
 [[19 22]
 [43 50]]
Matrix Multiplication using @ operator:
 [[19 22]
 [43 50]]
Matrix Multiplication using np.matmul():
 [[19 22]
 [43 50]]


In [ ]:
# to find the determinant
c = np.identity(3)
np.linalg.det(c)


np.float64(1.0)

### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(np.min(stats))
print(np.min(stats,axis=0)) # column wise smallest element
print(np.min(stats,axis=1)) # row wise smallest element
print(np.max(stats))
print(np.mean(stats))
print(np.median(stats))
print(np.sum(stats))
print(np.sum(stats, axis=1))
print(np.sum(stats, axis=0))

1
[1 2 3]
[1 4]
6
3.5
3.5
21
[ 6 15]
[5 7 9]


### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8,]])
print(before)
print(before.shape)

after = before.reshape(8,1)
print(after)

after1 = before.reshape(2,2,2)
print(after1)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking vectors (must have same columns)

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print(np.vstack([v1,v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Horizontal stack (must have same rows)

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1,"\n",h2)
print()

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 [[0. 0.]
 [0. 0.]]



array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

In [ ]:
# Load data from file

filedata = np.genfromtxt('data.txt',delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [ ]:
print(filedata.astype('int32')) # does not change the values permanently

print()

print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


### Boolean Masking & Advanced Indexing

In [ ]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
filedata[filedata > 50] # get the values from those indices

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [ ]:
# You can index with a list in numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
np.any(filedata > 50, axis=0) # column wise checking if there are no.s greater than 50

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(filedata>50, axis=0) # column in which all values are greater than 50

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])